# Generated by Django 5.0.1 on 2024-01-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/Default_pfp.png', upload_to='profile_pics/'),
        ),
    ]
