# Generated by Django 5.0.1 on 2024-01-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_profile', '0002_alter_profiledetails_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='bio',
            field=models.CharField(default='No bio', max_length=50),
        ),
    ]
